### ISSUE TITLE
Create data template file

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/checklist-recipe#1]
Create a csv, named `data/raw/checklist.xlsx` with the following fields:

- [x] `scientific_name`
- [x] `kingdom`
- [x] `taxon_rank`
- [x] `country_code`
- [x] `locality`
- [x] `occurrence_status`
- [x] `establishment_means`
- [x] `threat_status`
- [x] `source`
- [x] `remarks`

Not to include:

- taxonomic_status: scope of recipe is thematic checklists, rather than taxonomic checklist. Including this would mean we also have to support synonymy link
- vernacular_names: out of scope for now, would mean repetition of names for multiple rows of same taxon
- event_date: very specific to TrIAS
- habitat: useful for speciesProfile, but not used at GBIF yet, so out of scope for now

**Comment by LienReyserhove** [comment]
As discussed before, I think it is still interesting to include vernacular_names in the thematic checklist, as this is commonly used by researchers.

**Comment by peterdesmet** [comment]
Issue started as a task, which is now completed. Suggestion to incorporate a vernacular name extension could be submitted as a new issue.
