### ISSUE TITLE
Things to keep in mind when writing the recipe

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/checklist-recipe#14]
### Use of:

- Input vs raw data: `source data`
- dataset vs dataframe: `data frame` when talking about R code
- you vs we (first is correct)
- field vs variable: dropped the use of `variable` in favour of `term` (or field)
- recipe vs workflow: clear, `recipe` is the whole thing, `workflow` is data script data

### Use of recode() and case_when()

I would also use case_when to map `nomenclaturalCode`. Also,` eventDate` still needs to be mapped, for which we can also use `case_when`.

**Comment by peterdesmet** [comment]
- `eventDate` currently not part of mapping script.
- You and we are both used, where most appropriate
- I think we paid attention to the other differences, but you're welcome to review.

Closing issue.
