### ISSUE TITLE
Review pages

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/checklist-recipe#15]
Page | Writer | Reviewer/Rewriter | Status
--- | --- | --- | ---
Home | @peterdesmet | @damianooldoni | ok
Getting started | @peterdesmet | @damianooldoni | ok
Source data | @LienReyserhove | @peterdesmet | ok
R Markdown | @LienReyserhove | @peterdesmet | ok
Tidyverse functions | @LienReyserhove | @peterdesmet @damianooldoni | ok
Output data | @damianooldoni @peterdesmet | @peterdesmet | ok
Tidy data | @LienReyserhove | @damianooldoni | ok
Scientific names | @LienReyserhove @damianooldoni | @peterdesmet  | ok
Taxon ranks | @LienReyserhove @damianooldoni | @peterdesmet | ok 
Taxon IDs | @damianooldoni | @peterdesmet | ok
Taxon core | @damianooldoni | @peterdesmet | ok
Distribution extension | @LienReyserhove @damianooldoni | @peterdesmet | ok
GitHub | @damianooldoni | @peterdesmet | ok
Publishing data | @damianooldoni | @peterdesmet | ok
Examples | @damianooldoni | @peterdesmet | ok

**Comment by damianooldoni** [comment]
Maybe should we close this issue?

**Comment by peterdesmet** [comment]
Yes!
