### ISSUE TITLE
Start a recipe document

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/checklist-recipe#4]
The getting started guide is a step by step approach of **how to use the checklist-recipe to standardize your own checklist**. `recipe.md` in root.

## Getting started

1. Copy checklist-recipe (with invitation link)
2. Clone repo locally
3. Open R studio
4. Run all cells
5. Check what happened (nothing, but everything works)

## Exercise vs working mapping template

1. Either follow exercise (see steps there) OR use the functioning dwc_mapping.Rmd

## Mapping steps

_Note: see https://github.com/inbo/dwc-in-R/blob/master/src/dwc-mapping.Rmd#map-to-darwin-core-archive_

- Read data
- Pre-processing
- Creating taxon core (use unique)
- Creating distribution extension

## 3 different types of mapping

_Note: see https://github.com/inbo/dwc-in-R/blob/master/src/dwc-mapping.Rmd#mapping_

- Mapping static fields
- Mapping fields as is
- Recoding fields

## Pushing changes back to Github

_Some basic git skills, using rstudio (alternatively GitHub desktop)_

## Using IPT to publish

_Links to other material_

### Examples

_Link to existing TrIAS datasets_

**Comment by damianooldoni** [comment]
The [recipe.md](https://github.com/trias-project/checklist-recipe/blob/add_recipe/recipe.md) document is started in branch `add_recipe`.

**Comment by peterdesmet** [comment]
Long done, decided to move content to wiki (so the file is not cluttering and getting outdated in everyones repo). Closing.
