### ISSUE TITLE
Create dwc_mapping.Rmd

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/checklist-recipe#5]
Should be functional (i.e. it standardizes the example source data to Darwin Core) and act as an example that can be build upon.

Functionality to include:

- [x] `digest` to generate `taxonID`
- [x] Remove duplicates to create unique records in taxon core
- [x] `name_parse` to get `genus` and `taxonRank`
- [x] static mapping, e.g. `datasetName`
- [x] as is mapping, e.g. `locality`
- [x] `recode` mapping: `treatStatus` from full text to codes
- [x] `case_when` mapping: if `locality` is empty and `countryCode` is e.g. BE => use `Belgium` for `locality`

**Comment by LienReyserhove** [comment]
Note, the use of the nameparser function is not always that trustworthy, see [this issue](https://github.com/gbif/name-parser/issues/26). So are we still going to use it to generate information for `taxonRank` and `genus`?

**Comment by peterdesmet** [comment]
Would still use it, it’s still useful and introduces the concept of external/biodiversity specific services

**Comment by peterdesmet** [comment]
All done, closing.
